import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/allPage/layout/Navbar";
import Footer from "@/components/allPage/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    absolute : "",
    default : "KMTETI FT UGM - Keluarga Mahasisiwa Teknik Elektro dan Teknologi Informasi FT UGM",
    template: "%s | KMTETI FT UGM",
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <link rel="apple-touch-icon" sizes="180x180" href="/img/favicon/apple-touch-icon.png"></link>
      <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon/favicon-32x32.png"></link>
      <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon/favicon-16x16.png"></link>
      <link rel="manifest" href="/img/favicon/site.webmanifest"></link>
      <link rel="mask-icon" href="/img/favicon/safari-pinned-tab.svg" color="#5bbad5"></link>
      <meta name="msapplication-TileColor" content="#da532c" />
      <meta name="theme-color" content="#ffffff"></meta>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
